version: "3.9"

services:
  backend:
    build:
      dockerfile: Dockerfile.production
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend:
    build:
      dockerfile: Dockerfile.production
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app